spring:
  application:
    name: notification-service
  cloud:
    config:
      name: notification-service, eureka-client, kafka
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:40000"