spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nobleboyh/microservices-template
          search-paths: config-server-files/
  application:
    name: config-server
server:
  port: 0
