spring:
  application:
    name: service1
  cloud:
    config:
      name: service1,mysql,eureka-client
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:40000"

eureka:
  client:
    service-url: "http://localhost:6789"